#redis 连接池配置
jedis:
  pool:
    host: 101.200.137.83
    passwd: 123456
    port: 6379
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000

#mybatis
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

#DB
spring:
  datasource:
    url: jdbc:mysql://101.200.137.83:3306/test
    username: root
    password: Xiaoming250.
